
import type { Metadata } from "next";

import * as React from "react"

import "./globals.css";
import HeaderFooter from "./_components/layouts/HeaderFooter";
import { ThemeProvider } from "@/components/theme-provider";
import Image from "next/image";




// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });


export const metadata: Metadata = {
  title: "KitaHack",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (

    <html lang="en">
      <body
        className={`antialiased`}
      >

        {/* with theme */}
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >

          <HeaderFooter>
            

              <div className="absolute inset-0 w-full h-[24rem] z-[-20]">
                <Image
                  src="/images/gradient-navbar.png"
                  alt="Background"
                  layout="fill"
                  objectFit="cover"
                  className="opacity-80 [mask-image:linear-gradient(to_bottom,black_10%,transparent_70%)] md:[mask-image:linear-gradient(to_bottom,black_10%,transparent_90%)] backdrop-blur-lg"
                />
              </div>

              {children}
           
          
          </HeaderFooter>
        </ThemeProvider>

        {/* without theme */}
        {/* <HeaderFooter>
          {children}
        </HeaderFooter> */}

      </body>
    </html>
  );
}



