
import type { Metadata } from "next";

import * as React from "react"

import "./globals.css";
import HeaderFooter from "./_components/layouts/Header";
import Footer from "./_components/layouts/Footer";
import { SidebarProvider } from "@/components/ui/sidebar";



// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (

    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SidebarProvider className={"block"} defaultOpen={false}>
          <HeaderFooter />

          {children}

          <Footer />

        </SidebarProvider>
      </body>
    </html>
  );
}



